.github/workflows/linter.yml, Content/GUI/NewHotbar.cs, Content/GUI/Tree.cs, Content/Socketables/Socketable.cs, Core/Systems/SkillSystem/SkillPlayer.cs, Core/Systems/TreeSystem/Passive.cs, Core/Systems/TreeSystem/TreeSystem.cs
Resolves: #48
- Cleans up a few things
- Adds in the skill keybinds to the hotbar draw
- Updates the linter process to .net 8
.Replace was used to remove the "D" from the number row keybinds. Might need other adjustments later
=> feat(#48): cleanup a few things and add the skill keybinds to hotbar

Core/Systems/Affixes/ItemTypes/WeaponAffixes/ModifyHitAffixes.cs, Core/Systems/EntityModifier.cs, Core/Systems/ModPlayers/OnHitDeBuffer.cs, Core/Systems/ModPlayers/UniversalBuffingPlayer.cs
Implement a system to enable ease of on-hit buff application, for affixes, as well as a "template" for how to create some more advanced affixes in the future
=> Onhit buff application for affixes.

Core/PoTItem.cs
Resolves:
Fixes issue where Lunar/Solar items in the inventory used the wrong scaling matrix, breaking most UI if zoomed in.
=> fix issue with bad scaling matrix

Core/Systems/BuffBarSystem/BuffBarSystem.cs
Resolves:
Fixed buff icon clickboxes not matching their visual position.
=> fixed buff icon clickbox locations

Core/Systems/EntityModifier.cs
Resolves: #162 
The buffs were working correctly, the problem was actually everything else.
Linked the wrong issue in the commit, *ups*.
=> Tootlips display correct color for added and removed affixes.

Core/Systems/AltUseUISystem.cs
Resolves: #187 
Fixes unload of the alt use bar
=> fix(#187): Fixes unload of the alt use bar

Core/PoTItem.cs, Core/Systems/Affixes/Affix.cs, Core/Systems/AltUseUISystem.cs
could be optimized by removing strings - prefix and affix + (affix class) type names
=> feat: networking code for affixes - and items in general

Content/GUI/CloseableSmartUi.cs, Content/GUI/GUIDebuggingTools.cs, Content/GUI/PlayerStats/PlayerStatInnerPanel.cs, Content/GUI/PlayerStats/PlayerStatUIState.cs, Content/GUI/Quests/QuestDetailsPanel.cs, Content/GUI/Quests/QuestsUIState.cs, Content/GUI/Utilities/UICloseablePanel.cs
Resolves:
Fixes being able to click through character stat panel.
Some minor formatting outside of it.
=> fix clickthrough + cleanup

Content/Items/Gear/Weapons/Boomerangs/Boomerang.cs, Content/Items/Gear/Weapons/Bow/Bow.cs, Content/Items/Gear/Weapons/Sword/FireStarter.cs, Content/Items/Gear/Weapons/Sword/Sword.cs, Content/Items/Gear/Weapons/Whip/Whip.cs, Core/Systems/ModPlayers/ExpModPlayer.cs, Localization/en-US/Mods.PathOfTerraria.Gear.hjson, Localization/en-US/Mods.PathOfTerraria.Items.hjson, Localization/en-US/Mods.PathOfTerraria.Misc.hjson, PathOfTerraria.csproj
Resolves:
Added localization for all alt-use functions in the game currently that didn't already have them (Whips, Swords, Bows, Boomerangs).
Also fixed Fire Starter alt use only working when the alt isn't available.
=> localize alt uses, level up, fix firestarter alt

Core/Mechanics/Experience.cs
Resolves:
Experience now has a consistent speed, lazily homes in instead of perfectly homing in, and has cleaner code.
=> modify exp speed & clean up code

Content/GUI/PassiveTree/PassiveElement.cs, Content/GUI/PassiveTree/PassiveTreeInnerPanel.cs, Content/GUI/Utilities/UICloseablePanel.cs, Content/GUI/Utilities/UIDraggablePanel.cs, Core/Loaders/UILoading/SmartUIElement.cs, Core/Loaders/UILoading/UILoader.cs
Resolves: #206
Improves how block input is used, slightly - also fixes #206.
Many things to add to it for it to work well for future things but it seems to work as intended for currently implemented UI.
=> feat(#206): Bake input blocking into the SmartUiElement

Content/GUI/PlayerStats/PlayerStatInnerPanel.cs, Core/Loaders/UILoading/UILoader.cs, Core/Mechanics/Skill.cs
Resolves: #207 
Fixed UI states not properly adjusting to resolution changes. 
Add in check for Skill loading, defaulting to Berserk if the old Skill cannot be loaded properly.
Also removed some debug Main.NewText.
=> fix #207, remove debug in PlayerStatInnerPanel

Content/GUI/PlayerStats/PlayerStatUIState.cs, Content/GUI/Quests/QuestsUIState.cs, Content/GUI/Tooltip.cs
=> fix(#224): hovering passives shows text again

Content/GUI/ExpBar.cs, Content/GUI/PassiveTree/PassiveElement.cs, Content/GUI/Quests/QuestDetailsPanel.cs, Content/GUI/SkillsTree/SkillElement.cs, Content/GUI/SkillsTree/SkillsTreeInnerPanel.cs, Content/GUI/TreeState.cs, Core/Loaders/UILoading/SmartUIElement.cs, Core/Mechanics/Skill.cs, Core/Systems/ModPlayers/SkillPlayer.cs, Core/Systems/TreeSystem/Passive.cs, Helpers/GUIHelper.cs
Resolves: None
Add in a very barebones UI just for some simple testing
=> Very barebones skill UI for the time being

Content/Items/Gear/Gear.cs
Resolves: #202 
Fixes equipping non-PoTItem armor throwing.
=> Hover gear fix

Content/Items/Gear/VanillaItems/Clones/Flails/FlailLoader.cs, Content/Items/Gear/VanillaItems/Clones/Flails/GolemFist.cs, Content/Items/Gear/VanillaItems/Clones/Flails/KOCannon.cs, Content/Items/Gear/VanillaItems/Clones/Miscellaneous/MiscellaneousLoader.cs, Content/Items/Gear/VanillaItems/Clones/Miscellaneous/Zenith.cs
Resolves:
Made Zenith clone work properly.
Fixed Golem Fist and KO Cannon being held improperly.
=> fixed parity with zenith, golem fist, ko cannon

Content/GUI/NewHotbar.cs
Resolves: #300
Formats the tooltip consistently with the rest of the mod and adds a background for consistency and readability.
Follow-up to #295.
=> feat(#300): render tooltips with `Tooltip` api; consistent font and background rendering

API/Commands/SpawnOrbs.cs, Core/Systems/ExperienceSystem/Experience.cs, Core/Systems/ExperienceSystem/ExperienceModSystem.cs, Core/Systems/MobSystem/MobExperienceSystem.cs, Core/Systems/Networking/Handlers/ExperienceHandler.cs
Resolves:
Fixes build issues regarding recent experience system changes.
=> fix mod not building lol

Content/Items/Gear/Weapons/Battleaxe/CorruptedBattleaxe.cs
Resolves: #203
Changed where Corrupted Battleaxe handles changing `Item.noMelee` and `Item.noUseGraphic`, also changed how the projectile is shot.
_No comments_
=> Fix: Corrupted Battleaxe isn't missing its graphic after alt use anymmore

Common/ItemSpawner.cs, Core/Items/ItemDatabase.cs
Resolves:
Fixes ItemDatabase not including modded items.
=> fix bad loop condition

Common/Systems/Questing/Quest.cs, Common/Systems/Questing/QuestModPlayer.cs, Common/Systems/Questing/QuestStep.cs, Common/Systems/Questing/QuestStepTypes/ActionStep.cs, Common/Systems/Questing/QuestStepTypes/BringCount.cs, Common/Systems/Questing/QuestStepTypes/CollectCount.cs, Common/Systems/Questing/QuestStepTypes/ConditionCheck.cs, Common/Systems/Questing/QuestStepTypes/InteractWithNPC.cs, Common/Systems/Questing/QuestStepTypes/KillCount.cs, Common/Systems/Questing/QuestStepTypes/ParallelQuestStep.cs, Common/Systems/Questing/Quests/MainPath/BlacksmithStartQuest.cs, Common/Systems/Questing/Quests/TestQuest/TestQuest.cs, Common/Systems/Questing/Quests/TestQuest/TestQuestTwo.cs, Common/UI/Quests/QuestDetailsPanel.cs, Common/UI/Quests/QuestsUIState.cs, Common/UI/Quests/UISelectableQuest.cs, Common/UI/Quests/UISelectableQuestStep.cs, Common/UI/Utilities/UISimpleWrappableText.cs, Content/NPCs/Town/BlacksmithNPC.cs, Localization/en-US/Mods.PathOfTerraria.Quests.hjson
Resolves: #329
Fixes instancing issue with Quest steps.
Adds in BringCount, InteractWithNPC and ActionStep quest steps.
Fixes and localizes all steps.
Made Quests into singletons, removed now-useless code.
Updated UISelectableQuestStep - all are displayed instead of being added as you complete, they're colored to signify progress (green is done, subtle is locked), and they update alongside their progress.
Updated all quests to use new system(s).
=> Quest reworking

Common/Systems/Questing/Quests/TestQuest/TestQuestTwo.cs
Resolves:
Whoops! Forgot to build after a PR, fixed the build error I missed.
=> fix me forgetting to update a delegate

Common/Mechanics/SkillPassive.cs, Common/Mechanics/SkillPassiveBlocker.cs, Common/Systems/ModPlayers/SkillPassivePlayer.cs, Common/UI/SkillsTree/SkillPassiveElement.cs, Common/UI/SkillsTree/SkillTreeInnerPanel.cs, Content/SkillPassives/Magic/IceNovaSkillPassive.cs, Content/SkillPassives/Magic/NovaBlocker.cs, Content/Skills/Magic/Nova.cs, Core/Commands/GrantSkillPassiveCommand.cs
Resolves: #362
- Adds in SkillPassiveBlocker class to block skill passives from being allocated under certain conditions
- Added NovaBlocker class to block Nova skill passives from being allocated when one is already allocated
- Improved grantskillpassive command to take an amount of points to add, defaulting to 1
- Added a bunch more hooks for SkillPassives for allocation
- Cleanup
=> add in skill blockers, more hooks, and improve grantskillpassive command

Common/Systems/BossTracker.cs, Core/Items/PoTItemHelper.cs
Resolves: N/A
* Add downed king slime flag
* Standardizes the item level drops and no longer random generates between two numbers
=> feat: Add downed king slime flag

Common/NPCs/Dialogue/NPCTownDialogue.cs, Common/NPCs/Effects/NPCHitEffects.cs, Content/NPCs/Town/BarkeepNPC.cs, Content/NPCs/Town/BlacksmithNPC.cs, Content/NPCs/Town/HunterNPC.cs, Localization/en-US/Mods.PathOfTerraria.NPCs.hjson, PathOfTerraria.csproj
Resolves: No issue linked.
* Adds `NPCTownDialogue` component, which provides registration and handles dialogue options of town NPCs upon interaction.
* Changes `NPCDeathEffects` to `NPCHitEffecs`, which provides the same results as before, except now you can customize the spawn conditions of the effects.
_No response_
=> feat: dialogue & hit effects npc components

Common/Data/Mobs/Vanilla/WindyBalloon.json, Common/Systems/PassiveTreeSystem/PassiveTreeSystem.cs, Content/Items/Gear/Weapons/Sword/Sword.cs
Resolves:
* Increases use time of sword slightly. Seemed a bit fast.
* Adds in some XP data for Pre hardmode mobs
=> Playthrough things

Common/Subworlds/BossDomainSubworld.cs, Common/Subworlds/BossDomainSystem.cs, Common/Subworlds/BossDomains/EyeDomain.cs, Common/Subworlds/BossDomains/KingSlimeDomain.cs, Common/Systems/Networking/Handlers/SpawnNPCOnServerHandler.cs, Common/Systems/Networking/Networking.cs, Content/Tiles/BossDomain/EmbeddedEye.cs, Content/Tiles/BossDomain/EmbeddedSlimes.cs, Localization/en-US/Mods.PathOfTerraria.Generation.hjson
Resolves: n/a
Syncs EoC embedded eye tile
Adds in text to all signs in EoC domain
Adds in nicer system to sync time in domains
Adds in better checks for EmbeddedEye and EmbeddedSlime tiles
Adds in params for syncing NPC spawns, adds in velocity param
=> Sync Eye Domain

Common/World/Passes/RavencrestEntrancePass.cs
Resolves: #420
Adds in nice sloped base to Ravencrest entrance and polished it with decor.
=> significantly polish ravencrest entrance

Common/NPCs/OverheadDialogue/IOverheadDialogueNPC.cs, Common/NPCs/OverheadDialogue/OverheadDialogueGlobalNPC.cs, Common/NPCs/OverheadDialogue/OverheadDialogueInstance.cs, Common/NPCs/OverheadDialogue/OverheadDialogueUIState.cs, Common/UI/Utilities/UISimpleWrappableText.cs, Content/NPCs/Town/BarkeepNPC.cs, Content/NPCs/Town/BlacksmithNPC.cs, Content/NPCs/Town/HunterNPC.cs, Content/NPCs/Town/WizardNPC.cs, Localization/en-US/Mods.PathOfTerraria.NPCs.hjson
Resolves: #419
Adds in overhead dialogue for NPCs.
Adds in all dialogue localization for all current npcs.
This is a really fun system.
=> all of overhead dialogue

Common/Systems/Affixes/AffixTooltip.cs, Common/Systems/Affixes/AffixTooltipsHandler.cs, Common/Systems/Affixes/ItemAffix.cs, Common/Systems/Affixes/ItemTypes/PassiveAffixes.cs, Common/Systems/Affixes/ItemTypes/UniqueAffixes.cs
Resolves: #465 
Adds in corrupt affix tooltips.
=> add corrupted tooltips

Common/UI/Armor/UIGearInventory.cs, Common/UI/Armor/UIGearInventoryManager.cs
Resolves: #479
Resolves: #471
Forces the new armor UI to refresh each armor page to properly reflect the current player's inventory/armor.
=> fix armor refresh issue

Common/Systems/MobSystem/MobExperienceSystem.cs, Localization/en-US/Mods.PathOfTerraria.hjson
* Updates the text for the weapon swap system
* Removes the experience system from triggering on critters and friendly NPCs
=> Weapon swap text

Common/ItemSpawner.cs
N/A
* Fixes a few xml comments in the item spawner class
=> fix: a few incorrect xml tags

Content/Items/Currency/AscendantShard.cs, Content/Items/Currency/CorruptShard.cs, Content/Items/Currency/EchoingShard.cs, Content/Items/Currency/GlimmeringShard.cs, Content/Items/Currency/LimpidShard.cs, Content/Items/Currency/RadiantShard.cs, Content/Items/Currency/UnfoldingShard.cs
N/A
* Just adds some basic descriptions to the currencies so when needing to reference them in code you don't have to read the code to know what they do
=> chore: add some basic descriptions to currency items

Content/Items/Placeable/ArcaneObeliskItem.cs, Content/Tiles/ArcaneObeliskTile.cs
Resolves: #534
Resolves: #533
Adds in recipe for the Arcane Obelisk.
Adds in one-per-world exclusivity for the Arcane Obelisk.
=> add recipe, make only one obelisk per world

Content/Items/Currency/AscendantShard.cs, Content/Items/Currency/CorruptShard.cs, Content/Items/Currency/CurrencyShard.cs, Content/Items/Currency/GlimmeringShard.cs, Content/Items/Currency/LimpidShard.cs, Content/Items/Currency/RadiantShard.cs, Content/Items/Currency/UnfoldingShard.cs
Resolves: #532
Adds proper drop rates to all Currency Shards.
Removes some redundant code.
=> update currency shard drop rates

Common/Systems/MobSystem/MobAPRGSystem.cs
Fixes netID NPCs not having their name set properly.
=> Fix netID issue

Common/Systems/Questing/QuestModPlayer.cs
Fix QuestModPlayer not adding some quests to the dict, causing throws.
=> Fix quests being missed

Core/Commands/SpawnUniqueItemCommand.cs
Resolves: #525
Modifies spawn unique item command:
1. Is now `/uitem` instead of `/spawnuitem` for ease of development
2. Takes a `string name` as the first argument, moved position arguments to the end (why are they there?)
=> unique item command

Content/Tiles/Town/RavenStatue.cs
Resolves: #610 
- Makes Ravencrest Statue unbreakable
=> make ravencrest statue unbreakable

.github/workflows/publish.yml, scripts/increment-version.py
N/A
- Adds in a script that will increment the build version
=> ci: Add in increment build version script

.github/workflows/publish.yml
=> chore: add github token env variable

.github/workflows/publish.yml
=> ci: swap to deploy key for pulling

.github/workflows/publish.yml, .github/workflows/releaseNotes.yml
=> ci: adding in release note generation

Common/Data/MobRegistry.cs, Common/Systems/ModPlayers/AttributesPlayer.cs, Content/Items/Gear/Armor/Leggings/Boots.cs, Content/Items/Gear/Armor/Leggings/BurningRedBoots.cs, Content/Items/Gear/Armor/Leggings/Greaves.cs
N/A
- Make attributes player public for use with PoTOnline Mod
- Fixes an issue with some leggings not being able to be equipped
=> chore: make attributes player public for use with PoTOnline Mod

Common/Systems/Affixes/Affix.cs, Common/Systems/Affixes/MobAffix.cs, Common/Systems/Affixes/MobAffixIconDrawing.cs, Common/Systems/MobSystem/ArpgNPC.cs
- Makes MobAffixes sync on npcs properly
- Fixes zoom not working properly when hovering over an affixed NPC to see its affixes
=> fix mob affixes in mp, hover issue

Common/NPCs/AffixFreeNPCs.cs, Common/Systems/VanillaModifications/BossItemRemovals/BossGlobalItemDisabler.cs, Common/Systems/VanillaModifications/BossItemRemovals/DisableCultistSpawns.cs, Common/Systems/VanillaModifications/BossItemRemovals/DisableEoLSpawn.cs, Common/Systems/VanillaModifications/BossItemRemovals/DisableFishingFishron.cs, Common/Systems/VanillaModifications/BossItemRemovals/DisablePlanteraSpawning.cs, Common/Systems/VanillaModifications/BossItemRemovals/DisableRandomSpawns.cs, Common/Systems/VanillaModifications/BossItemRemovals/RemovePowerCells.cs
- Stops all bosses from being spawned with vanilla items or naturally
- Fixes EoC/King Slime being able to spawn naturally
=> Stop hm boss spawns

Common/Subworlds/BossDomains/BoCDomain/CrimsonMawPlayer.cs, Common/Systems/ItemTooltipBuilder.cs, Core/UI/UIManager.cs
- Cleanup
- Make ItemTooltipBuilder public so I can use it in the online mod
=> minor changes for associated online mod trading UI functionality

Common/UI/DropVisualization/DropTableUIState.cs, Common/UI/Elements/UIEditableText.cs, Common/UI/Elements/UIEditableValue.cs, Content/Items/Currency/AscendantShard.cs, Content/Items/Currency/CorruptShard.cs, Content/Items/Currency/EchoingShard.cs, Content/Items/Currency/GlimmeringShard.cs, Content/Items/Currency/LimpidShard.cs, Content/Items/Currency/MysticShard.cs, Content/Items/Currency/RadiantShard.cs, Content/Items/Currency/ShiftingShard.cs, Content/Items/Currency/UnfoldingShard.cs, Core/Items/PoTGlobalItem.Data.cs
- Publicize shards, ImplicitCount
- Added UIEditableText, not functional atm
- Rename EditableValueUI to UIEditableValue for consistency
=> Some sell UI stuff

Common/Data/Models/PassiveData.cs, Common/Data/Passives/Passives.json, Common/Systems/PassiveTreeSystem/Passive.cs, Content/Passives/AttributePassives.cs, Content/Passives/BlockPassives.cs, Content/Passives/BuffPassives.cs, Content/Passives/ClassPassives.cs, Content/Passives/CriticalPassives.cs, Content/Passives/JewelSocket.cs, Content/Passives/LifePassives.cs, Content/Passives/MagicRangedPassives.cs, Content/Passives/ManaPassives.cs, Content/Passives/MeleePassives.cs, Content/Passives/RangedPassives.cs, Content/Passives/StartPassive.cs, Content/Passives/SummonPassives.cs, Localization/en-US/Mods.PathOfTerraria.Passives.hjson, description.txt
N/A
* Adds a `Value` to Passive and allows you to set this in the passive data to have passives with different values
* Updates the description some with some new work and fixing of "Skilling" -> "Skills"
=> Passive updates

Common/ItemDropping/DropTable.cs, Common/Subworlds/MappingDomainSystem.cs, Common/Subworlds/MappingNPC.cs, Content/Items/Consumables/Maps/BossMaps/BeeMap.cs, Content/Items/Consumables/Maps/BossMaps/BoCMap.cs, Content/Items/Consumables/Maps/BossMaps/DeerclopsMap.cs, Content/Items/Consumables/Maps/BossMaps/EoCMap.cs, Content/Items/Consumables/Maps/BossMaps/EoWMap.cs, Content/Items/Consumables/Maps/BossMaps/KingSlimeMap.cs, Content/Items/Consumables/Maps/BossMaps/PrimeMap.cs, Content/Items/Consumables/Maps/BossMaps/QueenSlimeMap.cs, Content/Items/Consumables/Maps/BossMaps/SkeletronMap.cs, Content/Items/Consumables/Maps/BossMaps/TwinsMap.cs, Content/Items/Consumables/Maps/BossMaps/WoFMap.cs, Content/Items/Consumables/Maps/ForestMap.cs, Content/Items/Consumables/Maps/Map.cs
Resolves: #675 
- Adds in CanDrop abstract property to Map
- Adds in drop conditions to all current Maps
- Adds in MappingDomainSystem.TiersDownedTracker.CompletionsPerTier for easier logic
=> Map drop rework

Common/UI/Guide/TutorialPlayer.cs
Resolves: #727
- Fixes tutorial UI drawing over mouse
=> fix tutorial ui layer

Common/Systems/Questing/Quest.cs, Common/Systems/Questing/QuestStep.cs, Common/Systems/Questing/QuestStepTypes/ActionStep.cs, Common/Systems/Questing/QuestStepTypes/BringCount.cs, Common/Systems/Questing/QuestStepTypes/CollectCount.cs, Common/Systems/Questing/QuestStepTypes/ConditionCheck.cs, Common/Systems/Questing/QuestStepTypes/InteractWithNPC.cs, Common/Systems/Questing/QuestStepTypes/KillCount.cs, Common/Systems/Questing/QuestStepTypes/ParallelQuestStep.cs, Common/Systems/Questing/QuestStepTypes/SplitQuestStep.cs, Common/UI/Quests/QuestDetailsPanel.cs, Common/UI/Quests/UISelectableQuestStep.cs
Resolves: #699
- Significantly improves Quest step drawing, more flexible & clear and always in real time
=> Quest step display overhaul

build.txt
N/A
* increase build from deployment
=> chore: increase build from deployment

Common/UI/CloseableSmartUi.cs, Common/UI/DropVisualization/DropTableUIState.cs, Common/UI/GrimoireSelection/GrimoireSelectionUIState.cs, Common/UI/PlayerStats/PlayerStatUIState.cs, Common/UI/Quests/QuestsUIState.cs, Common/UI/TreeState.cs, Common/UI/Utilities/TabsUiState.cs, Core/UI/SmartUI/SmartUiElement.cs, Core/UI/SmartUI/SmartUiState.cs
N/A
* chore: add a few public accessibility to classes
* Removes extra call of add close button
* Moves GetRectangle up for shareability
=> chore: add a few public accessibility to classes

Common/UI/TreeState.cs, Common/UI/Utilities/TabsUiState.cs
* fix an issue with an infinite loop for the close button
* Was a change I made when making TabsUiState it seems
=> fix: an issue with an infinite loop for the close button

Common/Subworlds/BossDomains/Prehardmode/QueenBeeDomain.cs
Resolves: #776
- Heavily reduces variance of Queen Bee domain tunnels
- Forcefully places the player sensor TE on player sensor tiles
- Adds in honey lanterns to Queen Bee domain tunnels, adds in plant variety
=> make queen bee domain more consistent, work

Content/Tiles/Maps/BaseShrine.cs
- Fixes the HookPostOnPlace or w/e being before the CopyFrom for the tile data
Tile data is extremely finnicky, so if you ever see "bad tile object data" in logs report it to me ASAP. That system's given me days of work for minor issues. From what I can tell, this didn't cause issues, but who knows! Don't want it to cascade.
=> fixes hanging tiledata usage which may cause issues

Common/UI/Guide/TutorialUIState.cs, Common/UI/TreeState.cs, Common/UI/Utilities/TabsUiState.cs, Common/UI/Utilities/UICloseablePanel.cs, Common/UI/Utilities/UITabsPanel.cs
- Makes UITabsPanel a child of UIClosablePanel, removes redundancies
- Adjusts code to account for the above
This is for making the UI in the online mod work.
=> Fix tabs state

Common/Data/Affixes/MapAffixes.json, Common/NPCs/QuestMarkers/Vanilla/OldManMarkerNPC.cs, Common/Subworlds/ArenaEnemyNPC.cs, Common/Systems/MiscUtilities/SpawnerSystem.cs, Content/Tiles/BossDomain/HiveSpawner.cs, Content/Tiles/BossDomain/UnderworldSpawnerTile.cs
Resolves: #799
Resolves: #794
Resolves: #790
- Makes Old Man's custom profile data unload with the mod
- Makes arena NPCs despawn if no players are within a certain distance and returns spawner tiles if applicable
- Removes an unwanted MapBossHealthAffix tier
=> Misc fixes

Common/Systems/PassiveTreeSystem/PassiveTreeSystem.cs, Common/Systems/Questing/QuestStepTypes/InteractWithNPC.cs, Common/UI/PassiveTree/PassiveElement.cs, Content/Items/Pickups/HealingPotionPickup.cs, Content/Items/Pickups/ManaPotionPickup.cs, Content/Items/Pickups/PickupItem.cs, Content/Items/Pickups/PotionPickupDropper.cs
Resolves: #814
Resolves: #813
Resolves: #812
Resolves: #811
- Prevents health and mana potion drops from critter/friendly NPCs, and forces potions to despawn after 1 minute
- Shows progress for item gather quests in the UI
- Ensures passive tree selections are saved after the UI closes
=> QA and fixes

Common/ItemDropping/DropTable.cs, Common/ItemDropping/ItemSpawner.cs, Common/Systems/MobSystem/ArpgNPC.cs, Content/NPCs/Town/RavenNPC.cs, Content/Skills/Melee/MoltenShield.cs, Content/Skills/Ranged/BloodSiphon.cs, Content/Skills/Ranged/FetidCarapace.cs, Localization/en-US/Mods.PathOfTerraria.Items.hjson
Resolves: #806 
Resolves: #803 
Resolves: #804
- Adds in level effects to all existing exclusive skills
- Adjusts exclusive skills to use MaxCooldown instead of Cooldown as the max cooldown value
- Adds a tiny glow to the Raven
- Guarantees a Magic/Rare drop from Magic/Rare enemies, respectively
=> Continued misc fixes qa

Common/Subworlds/RavencrestSubworld.cs
Resolves: #848 
Fixes issue with ravencrest being stuck in night mode
=> fix(#848): issue with ravencrest being stuck in night mode

Content/NPCs/Mapping/Forest/GrovetenderBoss/RunestoneBurst.cs, Content/Skills/Magic/Nova.cs, Content/Skills/Ranged/RainOfArrows.cs, Localization/en-US/Mods.PathOfTerraria.Items.hjson
- Fixes Rain of Arrows bullets dealing no damage
- Improves Skill Augmentation Orb tooltip
- Makes Runestone Burst's death localization consistent in multiplayer
- Improves all Nova visual effects, especially the default
=> Skill updates

Common/Subworlds/MappingAreas/ForestArea.cs
=> make forest shrines not duplicate & be 1/5 instead of 1/1

Common/Enums/ItemType.cs, Common/Mechanics/Skill.cs, Common/UI/Hotbar/NewHotbar.cs, Content/Skills/Magic/Nova.cs, Content/Skills/Ranged/RainOfArrows.cs, Localization/en-US/Mods.PathOfTerraria.Gear.hjson, Localization/en-US/Mods.PathOfTerraria.Skills.hjson
Resolves: #844
- Localized some ItemType names, added helper method
- Added ModifyTooltips method to Skill, api around it
- Modified tooltips in Nova, Rain of Arrows to specify damage/weapon type needed
- Some reorganization
=> Add skill tooltipping API

Common/NPCs/AffixFreeNPCs.cs, Common/Subworlds/BossDomains/Prehardmode/QueenBeeDomain.cs, Common/Subworlds/BossDomains/Prehardmode/WallOfFleshDomain.cs, Common/UI/Guide/TutorialSystem.cs, Common/World/Generation/Tools/GenerationUtilities.cs, Content/NPCs/Mapping/Forest/Entling.cs, Content/NPCs/Mapping/Forest/GrovetenderBoss/RunestoneBurst.cs, Content/Skills/Magic/Fireball.cs, Content/Tiles/Furniture/MapDevicePlaceable.cs
Resolves: #873 
- Hides tutorial if you switch players midgame
- Blacklisted Skeletron hands, WoF eyes from affixes
- Fixed WoF domain not having functional player sensors, added helper method for that
- Fixed map device not working on some styles
- Fixed Runestone Bursts not drawing
- Increased cooldown for Fireball skill back to normal 8s instead of 2s
=> fixed a bunch of misc bugs

Common/Systems/Affixes/ItemTypes/DefenseAffixes.cs, Common/Systems/Affixes/ItemTypes/LifeAffixes.cs, Common/Systems/Affixes/ItemTypes/ManaAffixes.cs, Localization/en-US/Mods.PathOfTerraria.Affixes.hjson
Resolves: #960 
* Rounds affixes that should be rounded to the nearest whole
=> fix(#960): Rounds affixes that should be rounded to the nearest whole

Common/Systems/Skills/SkillTree.cs, Common/UI/SkillsTree/AugmentSlotElement.cs
- Fixes empty augmentation slots not loading safely
=> Augment load fix

Common/Mechanics/Skill.cs, Common/Systems/Questing/Quest.cs, Common/UI/Guide/TutorialUIState.cs
Resolves: #995 
*  Grants arcane obelisk when skipping all starter quest steps
=> fix(#995): Grants arcane obelisk when skipping all starter quest steps

Common/UI/Guide/TutorialUIState.cs, Localization/en-US/Mods.PathOfTerraria.UI.hjson
Resolves: #994
* Updates localization to be a bit more obvious to new players
* Condenses the step code for Tutorial a bit
=> fix(#994): Updates localization to be a bit more obvious to new players

Common/Config/UIConfig.cs, Common/Data/Passives/Passives.json, Common/Systems/Affixes/ItemTypes/PassiveAffixes.cs, Common/UI/ExpBar.cs, Common/UI/PassiveTree/PassiveTreeHotkey.cs, Content/Items/Gear/Weapons/WarShields/StarlightBulwark.cs, Content/Skills/Melee/Berserk.cs, Localization/en-US/Mods.PathOfTerraria.Configs.hjson, Localization/en-US/Mods.PathOfTerraria.hjson
* Just some syntax cleanup
* Changed berserk cooldown to 30 seconds
* Changed berserk duration to 5 seconds
* Added a hotkey to open the passive tree
* Added Mod Config option to turn off clicks on the experience bar
* Changes position of the Increased Whip Speed to not overlap
=> Collin fixes

Common/Systems/Networking/Networking.cs, Content/Items/Pickups/GrimoirePickups/OwlFeather.cs, Content/Tiles/Furniture/MapDevicePlaceable.cs
Resolves: #1072
Fixes Map Devices duplicating, not having a tile entity in MP.
=> fix map device in mp

Content/NPCs/Town/RhineNPC.cs, Content/Projectiles/Utility/EoWPortal.cs
- Actually removes EoW portal despawn condition
- Syncs the items Rhine gives you
=> rhine item syncing, eow portal despawn removal

Common/Data/Affixes/ArmorAffixes.json
N/A
- adjust the max potion counts. Way too strong early
=> chore: adjust the max potion counts. Way too strong early

Common/Systems/MiscUtilities/OrbBreakingMessage.cs, Common/UI/PlayerStats/PlayerStatInnerPanel.cs, Content/Projectiles/Utility/CrimsonMaw.cs, Localization/en-US/Mods.PathOfTerraria.UI.hjson, Localization/ru-RU/Mods.PathOfTerraria.UI.hjson
See title
Resolves: #1115 
list.Add(new PlayerStatUI(GetLocalization("MaxMinions"), player => $"{player.maxMinions.ToString()}"));
Didn't change the RU localization of this
=> Added a maximum minion count on stat sheet.

Core/Items/PoTGlobalItem.Tooltips.cs, Localization/en-US/Mods.PathOfTerraria.Gear.hjson, Localization/ru-RU/Mods.PathOfTerraria.Gear.hjson
Resolves: #1099
* Adds in a tooltip line for mana cost
=> feat(#1099): Adding in mana cost tooltip line

Common/Systems/Questing/QuestStep.cs, Common/UI/Quests/UISelectableQuest.cs
Resolves: #1125
* Increases quest book text size
=> feat(#1125): Increases quest book text size

Core/Items/PoTGlobalItem.Tooltips.cs
=> fix: damage rolls being incorrect ranges

Common/UI/Tooltip.cs, Content/Items/Pickups/GrimoirePickup.cs, Content/NPCs/BossDomain/Mech/Grabber.cs, Content/NPCs/Mapping/Desert/SunDevourer/WormLightning.cs
=> Miscellaneous fixes 25-08-13.

Common/Systems/ItemTooltipBuilder.cs
=> fix: Tooltips hotfix.

Common/Systems/ItemTooltipBuilder.cs, Common/Systems/Sockets/UnAndEquipSocketSystem.cs, Common/UI/Quests/QuestsUIState.cs, Common/UI/Quests/UISelectableQuest.cs, Common/UI/Quests/UISelectableQuestStep.cs, Common/UI/Utilities/BlockClickItem.cs, Content/Items/Gear/Weapons/Boomerangs/Boomerang.cs, Content/Items/Gear/Weapons/WarShields/WarShield.cs, Core/Commands/SpawnItemCommand.cs, build.txt
Resolves: #1292
Resolves: #1295
- War Shields and Boomerangs now have the right item level
- Completed quests are now selectable to see the steps again
- Completed quests can't be secretly pinned anymore
- Improved the spawnitem command a lot
=> various fixes

Common/UI/AllocatableInnerPanel.cs, Localization/de-DE/Mods.PathOfTerraria.Passives.hjson, Localization/es-ES/Mods.PathOfTerraria.Passives.hjson, Localization/pl-PL/Mods.PathOfTerraria.Passives.hjson, Localization/pt-BR/Mods.PathOfTerraria.Passives.hjson
Resolves: #1320
Fixed passives outside of the initial viewport not responding due to existing outside of the parent UI element.
=> Fix passives interaction

Core/Hooks/ItemAlwaysAllowEquipWith.cs
Fixes #1335 to work with the stable released version of tModLoader, that doesn't directly expose hooks for `AccCheck_ForPlayer`
=> Duplicate accessory check fix

Common/UI/Guide/TutorialNPCs.cs, Common/UI/Tooltip.cs, Common/UI/TooltipOverrides.cs
Resolves: #1344 
Resolves: #1345 
- Fixes Crimson/Corruption mobs not spawning in multiplayer
- Fixes autopause breaking some tooltips
Couldn't replicate any crashes on #1344. Should it be closed?
=> Two small fixes

Common/Systems/Affixes/ItemAffix.cs, Common/UI/SubworldHelp/SubworldHelpInvButton.cs
=> Use the maps `AreaLevel` to determine the tiers for the map affixes to show

Common/Systems/Questing/Quests/MainPath/WitchStartQuest.cs, Localization/de-DE/Mods.PathOfTerraria.NPCs.hjson, Localization/en-US/Mods.PathOfTerraria.NPCs.hjson, Localization/es-ES/Mods.PathOfTerraria.NPCs.hjson, Localization/pl-PL/Mods.PathOfTerraria.NPCs.hjson, Localization/pt-BR/Mods.PathOfTerraria.NPCs.hjson
Resolves: #1384
Adjusted text for the Ancient Art to be more clear on what to do.
=> clairfy Ancient Art quest steps

Common/Systems/DisableBuilding/BuildingWhitelist.cs, Common/Systems/DisableBuilding/StopExplodingTile.cs, Common/UI/ExpBar.cs, Content/NPCs/Town/TownScoutNPC.cs
- Completely blocked the block swap mechanic in all subworlds
- Fixed error where moving between domains wouldn't reset some building permissions
- Allowed the Goblin Surveyor to show up on the Life Analyzer for convenience
So is this the right branch to merge to? Or would I go to main?
=> stop platform block swap exploit, building permissions bleed
