Path-of-Terraria/PathOfTerraria

Core/Systems/HotbarHijack.cs, Localization/en-US_Mods.PathOfTerraria.hjson
Resolves: #62 
Detour Main.GUIHotbarDrawInner in order to stop invisible hotbar items from showing their hover name. This will only show the name of the first hotbar item; unsure if that's desired or not.
n/a
=> fix issue #62

PathOfTerraria.csproj, Properties/launchSettings.json
Resolves: #86 
Modifies the csproj and launchSettings.json files, creating some variables that decide which commands to use depending on OS
Switching to the `DotNetName` variable that the tmodloader targets file provides should work with most operating systems, the bulk of this is making it also work with NixOS
Need someone on windows to test if it works, I can test on arch linux to verify more normal distros work. Unsure if we have anyone with a mac, but if it works on linux it should work there
=> Modify launch and build commands to be more compatible with other platforms

Content/GUI/PassiveElement.cs, Core/Systems/TreeSystem/Passive.cs, Localization/en-US/Mods.PathOfTerraria.Passives.hjson, PathOfTerraria.csproj
Resolves: #73 
`Passive.Name` and `.Tooltip` now autogenerate localization in `Mods.PathOfTerraria.Passives`.
Unsure if `Name` and `Tooltip` should be preserved, since they have one use, once, during the first build after they're added.
=> add localization to passives per #73

Content/GUI/NewHotbar.cs, Localization/en-US/Mods.PathOfTerraria.Items.hjson, Localization/en-US/Mods.PathOfTerraria.Passives.hjson
Resolves: #123 
The combat bar now doesn't click onto other items since that'd be unclear.
The building bar does click onto other items, and has the proper clickboxes. Additionally, this adds back the hover name for each hover, aside from the first two items.
This also fixes the rendertarget hack used to hide the original hotbar breaking when zooming. Since the fix covers the item name, now we also draw the name manually - which looks better anyway. The item name also now uses the item's rarity color, which just looks fancy and there's never an excuse to not be fancy.
There's also a few minor tweaks to existing code, namely a brace pair that was just hanging out.
`HijackHotbarClick` is in the same file as `NewHotbar` since I'm unsure of where to put it. It's small enough …
=> Hotbar click fixes

Core/Systems/Affixes/ItemTypes/ArmorAffixes/DefenseAffixes.cs, Core/Systems/EntityModifier.cs, Core/Systems/ModPlayers/BuffModifierPlayer.cs
Resolves: #118
Added `ResistanceHelmetAffix` and `BuffBoostHelmetAffix`. Both are programmed to apply to helmets only. Their buffs are not final, but seem reasonable from my limited understanding of the affix system. 
These both use `BuffModifierPlayer`.
ResistanceHelmetAffix is marked as negative because it reduces values, even though -x% debuff time is good.
=> #118 + additional buff boost

Content/GUI/NewHotbar.cs, Core/Systems/HotbarHijack.cs
Resolves: #139
Rewrites handling of hotbar rendering to properly hide the vanilla hotbar. Recycles an existing detour to accomplish this.
The detour is designed to cleanly cancel vanilla behavior while preserving any new behavior added by mods. I could have gone with an IL edit instead to always branch to a `ret`, but this was faster and more immediately obvious in terms of functionality.
=> Fix New Hotbar Rendering

Content/GUI/NewHotbar.cs
Resolves: #141
Improves the hotkey rendering to be eased in alongside the hotbar and to be drawn with a black stroke a la other text in the hotbar.
Preliminary work for future changes to hotkey rendering.
=> feat(#141): make hotbar hotkeys ease in with the hotbar, draw with stroke

Core/PoTItem.cs, Localization/en-US/Mods.PathOfTerraria.hjson
Resolves: #143 
Corrects the internal name of the CopyItemInfo key and adds it to the localization files.
N/A
=> fix(#143): correct `CopyItemInfo` key name and add localization

Core/Systems/HotbarHijack.cs, Core/Systems/ModPlayers/ClassModPlayer.cs
Resolves: #80
- Simplifies existing hotbar item slot handling code. Adds another hook to handle picking up items.
- All tools are now considered tools for the hotbar, not just pickaxes.
- Starting inventory leaves the first slot empty, 2nd and 3rd are populated with tools as normal.
- Tools can now go in any slot.
N/A
=> fix(#80): all tools are hotbar tools, items enter correct hotbar slots, starting inventory corrected

Core/Systems/AltUseUISystem.cs
Resolves:
Fixes issue with divide-by-zero causing a crash when using an alt ability, exiting the world and re-entering.
=> fix alt use bar issue

Content/Items/Gear/VanillaItems/Clones/Boomerangs/BoomerangLoader.cs, Content/Items/Gear/VanillaItems/Clones/Flails/FlailLoader.cs, Content/Items/Gear/VanillaItems/Clones/Miscellaneous/MiscellaneousLoader.cs, Content/Items/Gear/VanillaItems/Clones/Miscellaneous/SolarEruption.cs, Content/Items/Gear/VanillaItems/Clones/Miscellaneous/Starlight.cs, Content/Items/Gear/VanillaItems/Clones/Miscellaneous/VampireKnives.cs, Content/Items/Gear/VanillaItems/InstancedVanillaClone.cs, Content/Items/Gear/VanillaItems/VanillaClone.cs, Content/Items/Gear/Weapons/Boomerangs/WoodenBoomerang.cs, Core/ManuallyLoadPoTItemAttribute.cs, Core/PoTItem.cs, Localization/en-US/Mods.PathOfTerraria.Items.hjson
Resolves: #244 
Adds in clones for all Boomerangs, Flails, and "Other" (Miscellaneous) weapons.
Added InstancedVanillaClone for manual loading through `Mod.AddContent`.
Added `PoTItem.ManuallyLoadPoTItem` & `PoTItem.ManuallyLoadedItems` to facilitate manually loaded PoTItems without throwing exceptions.
=> Boomerang flail other clones

Content/Items/Gear/GearAlternatives.cs, Core/PoTItem.cs, Localization/en-US/Mods.PathOfTerraria.Items.hjson, Localization/en-US/Mods.PathOfTerraria.Passives.hjson
Resolves: #247
Replaces all VanillaClones and other items registered in GearAlternatives with their PoTItem clones, with their proper rarity and affixes.
On main, there's currently no chest item to replace. Once #257 is replaced, there'll be a few to test with. For this, I just made a Flare Gun alternative and removed it when pushing.
=> replace vanilla w/ alternatives in chests

Content/Items/Gear/VanillaItems/InstancedVanillaClone.cs, Core/ItemSpawner.cs, Core/ManuallyLoadPoTItemAttribute.cs, Core/PoTItem.cs
Resolves: #265 
Fixes an issue where manually loaded PoTItems, namely InstancedVanillaClones, would throw an error upon using `/spawnitem` in-game due to `Activator.CreateInstance` expecting a parameterless ctor.
Reworked PoTItem.AllItems and all peripheral code to store item by ID instead of by `Type`, so a single `Type` can have more than one item.
Fixed all item spawning code to take an ID instead of a `Type`, and properly cloned the item instead of using `Activator.CreateInstance` with manually loaded items.
I did rewrite a good portion of PoTItem's autoloading. This should not change anything as the IoC will do it all automatically, and using `ItemSpawner.GetTypeFromId(int)` will get you the Type from an item ID automatically if needed.
=> fix autoloading issue with manually added PoTItems

Content/GUI/NewHotbar.cs
Resolves: #263 
Adds in hover tooltips to both the main weapon and pickaxe, on the combat and building hotbar respectively.
=> add in hotbar slots 0 and 1 tooltips

Core/Systems/ModPlayers/GearSwapManager.cs
Resolves: #288
Serializes a list of `TagCompound`s instead of an array due to poor handling of collection serialization on tModLoader's end.
I will be writing a ticket in the tML repo to address this oversight. Edit: [Done](https://github.com/tModLoader/tModLoader/issues/4316).
=> fix(#288): serialize a list of `TagCompound`s instead of an array

Content/GUI/NewHotbar.cs, Localization/en-US/Mods.PathOfTerraria.Misc.hjson
Resolves: #264 
Colors can be added to the tooltips later per anyone's request.
=> feat(#264): implement hoverable tooltips for health and mana potions

Core/Systems/BossTracker.cs
Resolves: #281 
Adds in `BossTracker.DownedEaterOfWorlds` and `DownedBrainOfCthulhu` flags. It also syncs these automatically in multiplayer.
=> add boss tracker for evil bosses

Core/Systems/DrawBlackPatch.cs
Resolves: #211 
Patches `DrawBlack` to draw the entire area it is expected to if in a subworld.
N/A
=> fix(#211): patch `DrawBlack` to force full area drawing in subworlds

Content/GUI/PlayerStats/PlayerStatInnerPanel.cs
Resolves: #291 
Tricks the game into correctly rendering the player in the stat panel by setting `Main::gameMenu` to true, includes a better approach in comments that is waiting on a tML bug to be fixed to be implemented.
https://github.com/tModLoader/tModLoader/issues/4317
=> fix(#291): render player in stat panel with white light

Content/Buffs/ArmorShredDebuff.cs, Content/Buffs/SmartBuff.cs, Content/Dusts/Sparkle.cs, Content/Items/Gear/VanillaItems/Clones/Swords/BrandoftheInferno.cs, Content/Items/Gear/Weapons/Battleaxe/Battleaxe.cs, Content/Items/Gear/Weapons/Boomerangs/Boomerang.cs, Content/Items/Gear/Weapons/Bow/Bow.cs, Content/Items/Gear/Weapons/Grimoire/GrimoireItem.cs, Content/Items/Gear/Weapons/Javelins/Javelin.cs, Content/Items/Gear/Weapons/Sword/BloodOath.cs, Content/Items/Gear/Weapons/Sword/Broadsword.cs, Content/Items/Gear/Weapons/Sword/CopperBroadsword.cs, Content/Items/Gear/Weapons/Sword/FireStarter.cs, Content/Items/Gear/Weapons/Sword/IronBroadsword.cs, Content/Items/Gear/Weapons/Sword/Katana.cs, Content/Items/Gear/Weapons/Sword/SteelBroadsword.cs, Content/Items/Gear/Weapons/Sword/StoneSword.cs, Content/Items/Gear/Weapons/Sword/WoodenSword.cs, Content/Items/Gear/Weapons/Whip/Whip.cs, Content/Items/Pickups/HealingPotionPickup.cs, Content/Items/Pickups/ManaPotionPickup.cs, Content/Items/Placeable/MapDevice.cs, Content/NPCs/Town/Barkeep.cs, Content/NPCs/Town/Blacksmith.cs, Content/Projectiles/LifeStealProjectile.cs, Content/Projectiles/Summoner/GrimoireSummon.cs, Content/Tiles/Town/BrokenAnvil.cs, Content/Tiles/Town/BrokenFurnace.cs, Core/Sources/SmartContentSource.cs, PathOfTerraria.cs
Resolves: #286
Implements `SmartContentSource` and removes redundant `Texture` overrides.
The remaining overrides to `Texture` are all necessary; we should probably standardize those ones too.
=> feat(#286): implement `SmartContentSource`, redirect asset requests to correct directory

Content/GUI/NewHotbar.cs, Content/Skills/Magic/Nova.cs, Content/Skills/Ranged/RainOfArrows.cs, Core/Mechanics/Skill.cs, Localization/en-US/Mods.PathOfTerraria.Skills.hjson
Resolves: #262
Adds in hover tooltips for each skill.
Fixes most skills not setting their needed weapon type (though that seems to do nothing?)
=> add skill tooltips, fix missing data on nova and rain of arrows

Common/UI/Armor/UIGearInventoryManager.cs, Core/UI/UIManager.cs, Localization/en-US/Mods.PathOfTerraria.Configs.hjson
Resolves: #229 
* Adds a new user interface system which relies solely around `UIState`, with no extra levels of abstraction.
* Adds the capability of enabling, disabling, toggling and retrieving registered `UIState` instances on demand.
* Adds the capability of hot reload support, although not implemented, its implementation is facilitated.
Enabling a state:
```csharp
[Autoload(Side = ModSide.Client)]
public sealed class UIGearInventoryManager : ModSystem
{
public const string Identifier = $"{PoTMod.ModName}:Inventory";
public override void OnWorldLoad()
{
UIManager.Enable(Identifier, "Vanilla: Inventory", new UIGearInventory(), 1);
}
}
```
Toggling a state:
```csharp
// For debugging purposes.
public override void PostUpdateInput()
{
if (!Main.keyState.IsKeyDown(Keys.F) …
```
=> feature: new ui system

Common/Systems/WorldNavigation/WorldNavigation.cs
Resolves: issue not made
Changed the path to include the `Assets` directory in front.
=> Fix: Wrong search path for Ravencrest world files

Common/UI/Armor/UIGearInventoryManager.cs, Core/UI/UIHotReloadUpdateHandler.cs, Core/UI/UIManager.Reload.cs, Core/UI/UIManager.cs
Resolves: No issue linked.
* Adds `UIState` IDE hot reload support.
This significantly boosts development since now you don't have to do manual workarounds or restart the mod every time you change something in a `UIState` regarding initialization, or generally speaking logic that only runs once upon activation.
Hot reloading will reset `UserInterface.CurrentState` and call `UIState::OnInitialize`.
=> feature: user interface hot reloading

Common/Data/Passives.json, Common/Systems/TreeSystem/TreeSystem.cs, Content/Passives/ClassPassives.cs, Content/Passives/SummonPassives.cs, Localization/en-US/Mods.PathOfTerraria.Passives.hjson
Resolves: #328 
Fixes Passives.json using outdated internal identifiers instead of internal class names for data, which fixes the NullRef.
=> make passives use internal name instead of old internal identifier

Core/Items/PoTGlobalItem.Data.cs
Resolves: #334
Fixes PoTInstanceItemData data not being shared properly between clones. Namely, Affixes persist now.
=> Fix PoTInstanceItemData bad cloning

Content/Items/Gear/Weapons/Battleaxe/Battleaxe.cs, Content/Items/Gear/Weapons/Battleaxe/CorruptedBattleaxe.cs, Content/Items/Gear/Weapons/Battleaxe/GuardianAngel.cs, Content/Items/Gear/Weapons/Boomerangs/Boomerang.cs, Content/Items/Gear/Weapons/Bow/Bow.cs, Content/Items/Gear/Weapons/Grimoire/GrimoireItem.cs, Content/Items/Gear/Weapons/Javelins/Bloodclotter.cs, Content/Items/Gear/Weapons/Javelins/Javelin.cs, Content/Items/Gear/Weapons/Javelins/MoltenDangpa.cs, Content/Items/Gear/Weapons/Javelins/Rottenbone.cs, Content/Items/Gear/Weapons/Sword/BloodOath.cs, Content/Items/Gear/Weapons/Sword/FireStarter.cs, Content/Items/Gear/Weapons/Sword/Sword.cs, Content/Items/Gear/Weapons/WarShields/StarlightBulwark.cs, Content/Items/Gear/Weapons/WarShields/WarShield.cs, Content/Items/Gear/Weapons/Whip/Whip.cs, Core/Items/PoTGlobalItem.Data.cs, Core/Items/PoTGlobalItem.Tooltips.cs, Localization/en-US/Mods.PathOfTerraria.Items.hjson
Resolves:
`PoTStaticItemData.Description` and `PoTStaticItemData.AltUseDescription` are now LocalizedTexts which update when language is changed.
All remaining uniques now have little flavor text descriptions.
=> Localize static data

Common/UI/Armor/UIGearInventory.cs
Resolves: #342 
Fixes inconsistent hovering in the inventory loadout buttons by setting `Player.mouseInterface` to true during hover.
Apparently UI elements don't automatically account for setting that field during collisions, we might want to keep an eye out.
=> fix: inconsistent loadout buttons

Common/UI/TreeState.cs
Resolves: #344 
Fixes various hovered text overlapping the Tree UI.
You can still talk to NPCs, open grave text boxes, and any similar functionality. This matches vanilla's functionality for some reason.
=> fix hover text in tree

Common/Mechanics/Skill.cs, Common/Mechanics/SkillPassive.cs, Common/Systems/ModPlayers/SkilPassivePlayer.cs, Common/UI/SkillsTree/SkillPassiveElement.cs, Content/SkillPassives/Magic/FireNovaSkillPassive.cs, Content/SkillPassives/Magic/IceNovaSkillPassive.cs, Content/SkillPassives/Magic/LightningNovaSkillPassive.cs, Content/SkillPassives/SkillPassiveAnchor.cs, Content/Skills/Magic/Nova.cs, Localization/en-US/Mods.PathOfTerraria.SkillPassives.hjson
Resolves: #357 
* Adds the ability for SkillPassives to be used across multiple skills - For things like the anchor or maybe generic damage in the future
* Fixes some localization things
* Fixes the AllocatePassivePoint method
=> feat(#357): Add ability to allocate skill passives

Common/UI/PassiveTree/PassiveElement.cs
Resolves: #355
Fixes passives tree being useless as the Anchor passive is locked. Hardcoded, which is unfortunate.
=> Fix "locked" anchor passive

Common/Systems/ModPlayers/SkillCombatPlayer.cs, Common/UI/SkillsTree/SkillSelectionElement.cs, Common/UI/SkillsTree/SkillSelectionPanel.cs
Resolves: #356
- Adds in "level/maxlevels" text over skills on the skill tree.
- Adds in "Skill cannot be added." message when applying a skill that cannot be equipped.
- Renames "DrawSkillTree" to "RebuildTree".
=> Add levels, add failure check, rename method

Common/NPCs/Effects/NPCHitEffects.cs, Common/Systems/ModPlayers/GrimoireSummonPlayer.cs, Common/UI/GrimoireSelection/GrimoireInvButton.cs, Common/UI/Utilities/UiStateRefresher.cs, Content/Items/Gear/Weapons/Grimoire/GrimoireItem.cs, Content/NPCs/BossDomain/BrainDomain/Minera.cs, Content/NPCs/Town/BarkeepNPC.cs, Content/NPCs/Town/BlacksmithNPC.cs, Content/NPCs/Town/HunterNPC.cs, Localization/en-US/Mods.PathOfTerraria.Affixes.hjson
Resolves: #387
Adds in flag for if the player has obtained a Grimoire.
Hides the Grimoire UI if the above flag is false.
Fixed Minera's reference to an nonexistent NPC component.
Added NPCHitEffects.OnDeath for ease-of-use on death effects.
=> fix minera, hide grimoire button until grimoire is obtained

Common/Systems/ModPlayers/PersistentReturningPlayer.cs, Content/Tiles/Town/RavenStatue.cs
Resolves: #402
Adds in persistent return location on Ravencrest Statue travel. This can be used later on anything else that needs it.
=> add in persistent returning

Common/Systems/PassiveTreeSystem/PassiveTreeSystem.cs, Common/UI/PassiveTree/PassiveElement.cs
Fixes interface showing -1 in the skill tree when player saves as new character and re-enters world.
Resolves: [#389](https://github.com/Path-of-Terraria/PathOfTerraria/issues/389)
Changes hard-coded value of 1->0 for AnchorPassive
Characters already affected by this issue will need to save and quit for fix to take place.
=> Changed default AnchorPassive value 1->0

Common/Subworlds/BossDomainSystem.cs, Common/Subworlds/BossDomains/BrainDomain.cs, Common/Subworlds/BossDomains/DeerclopsDomain.cs, Common/Subworlds/BossDomains/EaterDomain.cs, Common/Subworlds/BossDomains/EyeDomain.cs, Common/Subworlds/BossDomains/QueenBeeDomain.cs, Common/Subworlds/BossDomains/SkeleDomain/RoomData.cs, Common/Subworlds/BossDomains/SkeleDomain/RoomDatabase.cs, Common/Subworlds/BossDomains/SkeletronDomain.cs, Common/Subworlds/BossDomains/WallOfFleshDomain.cs, Common/Subworlds/BossDomains/WoFDomain/ArenaEnemyNPC.cs, Common/Subworlds/BossDomains/WoFDomain/WoFDomainSystem.cs, Common/Systems/MiscUtilities/BlockerSystem.cs, Content/NPCs/BossDomain/SkeletronDomain/ControllableSpikeball.cs, Content/Projectiles/Teleportal.cs, Content/Tiles/BossDomain/CorruptSacks.cs, Content/Tiles/BossDomain/HiveSpawner.cs, Content/Tiles/BossDomain/Pustule.cs, Content/Tiles/BossDomain/UnderworldSpawnerTile.cs, Localization/en-US/Mods.PathOfTerraria.Generation.hjson
Resolves: n/a
Syncs and improves every single domain. Specifically,
Eater: Fixes arena check, spawn change, egg prefab placement (shouldn't block passages now), corrupt sack spawning in mp. updates time, adds in sign text
Brain of Cthulhu: Fixes time, arena & spawn check, 
Queen Bee: Fixes lack of randomization on rooms, updates time
Deerclops: Fixes time, spawn check, poor structure placement,
Skeletron: Fixes spikeball placement, syncing, arena check
Wall of Flesh: Fixes camera restriction
This was originally going to be just EoW, but it was so quick I just did the rest. Sorry for the larger PR!
=> Sync every remaining domain

Common/Enums/ItemType.cs, Common/Systems/Affixes/AffixTooltipsHandler.cs, Common/Systems/Affixes/ItemTypes/ModifyHitAffixes.cs, Common/Systems/Affixes/ItemTypes/PassiveAffixes.cs, Common/Systems/MobSystem/MobAPRGSystem.cs, Content/Items/Currency/GlimmeringShard.cs, Content/Items/Gear/Weapons/Boomerangs/Boomerang.cs, Content/Items/Gear/Weapons/Bow/Bow.cs, Content/Items/Gear/Weapons/Grimoire/GrimoireItem.cs, Content/Items/Gear/Weapons/Javelins/Javelin.cs, Content/Items/Gear/Weapons/Staff/Staff.cs, Content/Items/Gear/Weapons/Sword/BloodOath.cs, Content/Items/Gear/Weapons/WarShields/StarlightBulwark.cs, Content/Items/Gear/Weapons/WarShields/WarShield.cs, Content/Items/Gear/Weapons/Whip/Whip.cs, Core/Items/PoTGlobalItem.Data.cs, Core/Items/PoTGlobalItem.Tooltips.cs, Core/Items/PoTGlobalItem.cs, Core/Items/PoTItemHelper.cs, Localization/en-US/Mods.PathOfTerraria.Gear.hjson, Localization/en-US/Mods.PathOfTerraria.Items.hjson
Resolves: #436
- Makes Magic rarity items roll either 1 or 2 affixes, not just always 2
- Adds in ItemTypes for Javelins, Grimoires, WarShields, Whips, and updates the class entries to have the new flags
- Fixes crash in AffixTooltipsHandler caused by having 2 sources for the same value
- Fixed BuffPoisonedHitsAffix being 100x stronger than it should be
- Adjusted IncreasedDamageAffix to be balanced and display the proper value
- Fixed IncreasedDamageAffix displaying the wrong value in tooltips
- Fix all Gear items which override HoldItem not calling base, thus breaking the tooltipping functionality Gear runs
- Fix PoTInstanceItemData.SpecialName not being set for vanilla items that are crafted
- Fix PoTItem names lack of localization
- Stop PoTGlobalItem from rolling …
=> Fix Affixes & Many More

Common/Data/AffixRegistry.cs, Common/Data/Affixes/ModifyHitAffixes.json, Common/Data/Affixes/OnKillAffixes.json, Common/Data/Affixes/PassiveAffixes.json, Common/Systems/ModPlayers/GrimoireStoragePlayer.cs, Common/UI/GrimoireSelection/GrimoireSelectionUIState.cs, Common/UI/Tooltip.cs, Content/Items/Gear/Gear.cs, Content/Items/Pickups/GrimoirePickup.cs, Content/Items/Pickups/GrimoirePickups/OwlFeather.cs, Content/Projectiles/Summoner/GrimoireSummon.cs
- Adds in a trash slot & trash functionality to Grimoire storage, so you can remove unwanted Grimoire material
- Fixes Grimoire summons not having any affixes, nor being able to roll them
- Improves tooltip functionality for Grimoire storage hover, Gear holding
- Fixes issue where you could fill up your Grimoire storage with empty items
I was just looking to make sure Grimoire worked before writing the wiki page...good thing I did!
=> Fix grimoire

Common/UI/Armor/UIGearInventory.cs, Common/UI/Armor/UIGearInventoryManager.cs, Common/UI/Armor/VanillaUIEdits.cs, Core/UI/UIManager.cs
Resolves: #459
Adjusts position of PvP elements next to the armor slots to remove overlap. Also makes it slide in alongside the armor UI.
Random cleanup.
=> Pvp icon adjustment

Common/Systems/Affixes/ItemTypes/LifeAffixes.cs, Content/Items/Gear/Armor/Helmet/Helmet.cs
Resolves: #473 
Fixes bad multiplication in MultipliedLifeAffix affix (multiplying by x% instead of (1 + x)%).
=> Max health affix fix

Common/UI/Elements/UIImageItemSlot.cs
Resolves: #478
Fixes main hand (and probably other slots) being offset if a large item is added to their slot.
=> fix mainhand offset

Common/Subworlds/RavencrestSubworld.cs, Common/Systems/MappingSystem.cs
Resolves: #502
Fixes code intended to stop spawns in Ravencrest from running everywhere.
=> fix ravencrest subworld removing all spawns lol

Content/Items/Gear/Gear.cs, Core/Items/PoTGlobalItem.Tooltips.cs, Core/Items/PoTItemHelper.cs
Resolves: #510
- Makes GenerateImplicits always run.
- Applies `IPoTGlobalItem` to `Gear` to guarantee all child classes have the associated data.
=> fix some Gear not being given a PoTGlobalItem, fix implicits

Common/Projectiles/ISaveProjectile.cs, Common/Projectiles/SaveProjectileSystem.cs, Content/Projectiles/Summoner/GrimoireSummons/HornetSummon.cs, Content/Projectiles/Utility/EoWPortal.cs, Content/Projectiles/Utility/EyePortal.cs, Content/Projectiles/Utility/QueenBeePortal.cs
Resolves: #476
Adds in ISaveProjectile interface for keeping projectiles active between saves (including entering & exiting subworlds).
Uses the above to save use count for each existing portal (EoW, EoC, Queen Bee).
Fixes the Queen Bee portal only spawning post-queen bee (aka it's impossible to spawn).
Made all portals despawn on their boss being killed, such that they're only accessible before beating the boss.
=> Add use counts to portals

Common/UI/Hotbar/NewHotbar.cs
Resolves: #557
Fixes Lesser Mana and Health Potions not showing up in hotbar UI.
DragonLens loads all item images when opened, which means I missed this usually.
=> Load potions in hotbar

Common/Systems/Questing/QuestModPlayer.cs, Common/UI/QuestPanelButton.cs
Resolves:
- Hide quest icon in inventory before first quest
- Flip FirstQuest saving pattern - this means it doesn't have to save after the player gets their first quest, saving a completely negligible amount of disk space
=> hide quest button before first quest; flip FirstQuest saving pattern

Common/NPCs/OnDeathNPC.cs, Common/Subworlds/RavencrestContent/RavencrestSystem.cs, Common/Systems/BossTracker.cs, Common/Systems/ModPlayers/ExpModPlayer.cs, Common/World/Passes/RavencrestEntrancePass.cs, Content/NPCs/Town/RavenNPC.cs
Resolves: #553
- Moves WoF death effect box to its own file for cleanliness
- Reworks Raven spawn pass to be used during gameplay, on level up from 0 to 1 (only once per world)
- Make Raven fade in so if it spawns near a player it's not jarring
=> clean up on death effect, spawn raven on first level up in the world

Common/UI/DraggableSmartUi.cs, Common/UI/PassiveTree/PassiveTreeInnerPanel.cs, Common/UI/TreeState.cs, Localization/en-US/Mods.PathOfTerraria.Passives.hjson
Resolves: #565
- Increases the size of the passive tree to be almost the full size of the screen, some buffer due to UI overlap
- Fixes AddedMinionDamagePassive broken localization
We'll definitely still want zoom on the UI in the future, we'll see where we are on the playtest.
=> Passive UI zoom

Content/Items/Gear/Weapons/Sword/CopperBroadsword.cs, Content/Items/Gear/Weapons/Sword/IronBroadsword.cs, Content/Items/Gear/Weapons/Sword/SteelBroadsword.cs
Resolves: #583
Makes all XBroadsword items inherit from Broadsword instead of Sword.
=> fix some swords not inheriting from broadsword

Common/UI/Tooltip.cs, Content/Items/Gear/Armor/Leggings/BurningRedBoots.cs, Core/Items/PoTGlobalItem.Tooltips.cs
Resolves: #613 
- Renames BruningRedBoots.cs to BurningRedBoots.cs
- Removes color tag from the Boot's name
- Recolors the ItemName tooltipline instead, makes that persist & override the PoT itemname
It's a little awkward to recolor names...I'm not sure why the Burning Red Boots do this, as they're the only item to do so, but yeah. In the hover tag, the name is a default white. I can change this if desired; either way, the erroneous tag is fixed.
=> Rename burning red boots, adjust color

Content/Items/Gear/Armor/Chestplate/BodyArmor.cs, Content/Items/Gear/Armor/Chestplate/Breastplate.cs, Content/Items/Gear/Armor/Chestplate/Chestplate.cs, Content/Items/Gear/Armor/Helmet/Crown.cs, Content/Items/Gear/Armor/Helmet/Helmet.cs, Content/Items/Gear/Armor/Helmet/Visor.cs, Content/Items/Gear/Armor/Leggings/Leggings.cs, Content/Items/Gear/Armor/Leggings/Tassets.cs, Content/Items/Gear/Armor/Leggings/Treads.cs
Resolves: #602 
- Spams the AutoloadEquip attribute on all of our armor Gear
This is fun. 
The issue was twofold: while our predicates for the armor slots are fine and functional, they still work with the underlying vanilla logic. So the legs slot still needs to be an item with a leg equip slot.
This brings us to issue two - the AutoloadEquip attribute *is not* inherited to children classes. This means the solution was applying it to every individual class. Fun!
I've documented this annoyance for clarity.
=> Fix equips failing

Content/Items/Pickups/PotionPickupDropper.cs
Resolves: #622 
- Made enemies drop health and mana potions at a 1/7 chance
- Fixed existing code that made a rule for bosses to drop a health potion on death that was never added to the loot pool
=> Make enemies drop potions

Common/UI/TreeState.cs
Resolves: #621 
Properly closes the passives/skill tree when using escape.
This is the easiest PR I've ever done anywhere
=> Fix escape to close tree

Common/Subworlds/RavencrestSubworld.cs, Content/NPCs/Town/TownScoutNPC.cs
Resolves: #601 
- Ravencrest, on first entered, would default to hardmode. Disabled that.
- Fixed and/or updated Goblin Scout spawn in Ravencrest
=> fix: ravencrest defaulting to hardmode

Common/Subworlds/BossDomains/DeerDomain/DeerclopsSpawnEdits.cs, Common/Subworlds/BossDomains/DeerclopsDomain.cs
Resolves: #615 
- Widens the semi-vertical chasms of the Deerclops domain & makes the chasm's "points" less far apart
- Sets spawn rate to a fixed rate, adding consistency and fixing weird issue with DragonLens(?)
=> fix(#615): fix spawn issue & widen chasms

Common/Systems/HellEvent/HellEventSystem.cs, Common/Systems/Questing/Quest.cs, Content/Items/Gear/Weapons/Bow/Bow.cs, Content/Items/Gear/Weapons/Sword/BloodOath.cs, Content/Items/Gear/Weapons/Sword/DwarvenGreatsword.cs, Content/Items/Gear/Weapons/Sword/FireStarter.cs, Content/Items/Gear/Weapons/Sword/StoneSword.cs, Content/Items/Gear/Weapons/Sword/WoodenSword.cs, Content/NPCs/Town/RhineNPC.cs
- Improves Hell Event ("hell earthquake") conditions by making it quicker to check, fixes inconsistency
- Fixes Rhine poorly checking if her quest can be taken
- Removes ItemLevel property a bunch of items had for some reason
- Adds generic overload to Quest.GetSingleton
=> fix: hell event conditioning, rhine quest check, remove old code

Common/Systems/Affixes/Affix.cs, Content/Items/Currency/CorruptShard.cs, Content/Items/Gear/Amulets/AddedLife/VigorAmulet.cs, Content/Items/Gear/Rings/AddedDamage/StoneRing.cs, Content/Items/Gear/Weapons/Battleaxe/CorruptedBattleaxe.cs, Content/Items/Gear/Weapons/Battleaxe/GuardianAngel.cs, Content/Items/Gear/Weapons/Battleaxe/IronBattleaxe.cs, Content/Items/Gear/Weapons/Javelins/Bloodclotter.cs, Content/Items/Gear/Weapons/Javelins/MoltenDangpa.cs, Content/Items/Gear/Weapons/Javelins/Rottenbone.cs, Content/Items/Gear/Weapons/Sword/BloodOath.cs, Content/Items/Gear/Weapons/Sword/DwarvenGreatsword.cs, Content/Items/Gear/Weapons/Sword/FireStarter.cs, Content/Items/Gear/Weapons/WarShields/StarlightBulwark.cs, Core/Commands/SpawnUniqueItemCommand.cs, Core/Items/PoTItemHelper.cs
Resolves: #606
- Updates all uniques to use Generate Affixes instead for their affixes
- Updates the uitem command and removes the quality increase parameter
- Normalizes the item level table
- Fixes Corrupted Battleaxe not getting the correct affixes
- Removes items getting influence over the item level of 50
- Fixes several uniques that had incorrectly assigned affix values
- Adds documentation around CreateAffix
=> Fix/606 Generate Affix Updates

Content/Items/Gear/Weapons/Bow/Twinbow.cs, Core/Items/PoTGlobalItem.cs
- Makes all PoTGlobalItem items set if they're unique & roll in SetDefaults
This does NOT make DragonLens or other cheat mod items roll rarity; this could be done trivially if desired. This DOES mean you can just pull out any unique, and it'll be a proper unique with all the affixes it should have. Finally.
=> Unique roll fix

Common/UI/Hotbar/NewHotbar.cs, Localization/en-US/Mods.PathOfTerraria.Skills.hjson
Resolves: #561 
* Trims skill keybind names if they're too long
* Shows the full skill keybind name in its tooltip
Unfortunately, `Tooltip` provides practically nothing regarding text customization. That is, different scales, colors, fonts, etc. which results in everything being crumpled together on the tooltip.
=> feat(#561): adds better hotkey tooltips for skills

Content/Items/Gear/Amulets/AddedLife/VigorAmulet.cs, Core/Items/PoTItemHelper.cs
- Fixed GenerateImplicits never being called
- Fixed VigorAmulet giving negative stats unintentionally
=> fix implicits not being called, fix negative affix on vigoramulet

Content/Items/Pickups/PotionPickupDropper.cs
- Fixes health & mana potion pickups taking up 4 slots on every enemy's bestiary loot drops
=> Pickup potions bestiary fix

Common/Systems/Questing/QuestUnlockManager.cs
- Fixes KeyNotFoundException being thrown by a Clothier's checking if a quest is available when you load into a world with him nearby
This error would likely persist for other NPCs and other checks too.
=> fix CanStartQuest early throw

Common/UI/Hotbar/NewHotbar.cs
Fixes item hover name displaying for the adjusted, new hotbar when in the inventory.
=> fix item hover issue with inventory open

Common/NPCs/QuestMarkers/Vanilla/OldManMarkerNPC.cs, Common/Systems/MapContent/QuestMarkerHook.cs, Localization/en-US/Mods.PathOfTerraria.NPCs.hjson
Resolves: #497 
- Hides quest icons from displaying when in undiscovered areas
- Stops the Old Man's icon from rendering & showing hover text when not discovered, to hide the Dungeon before discovery
=> Hide undiscovered quest markers

Common/Data/AffixRegistry.cs, Common/Data/Models/AffixData.cs, Common/Systems/Affixes/Affix.cs
- GetAppropriateTierData gives the *index* of the tier that was chosen; higher number = stronger.
This is stored by index, so if displayed, this should be shown as `index + 1`.
- Adds in non-generic overloads for Affix.CreateAffix
- Stores affix tier on item affixes
=> changes to facilitate online trading

Core/Items/PoTGlobalItem.Tooltips.cs, Localization/en-US/Mods.PathOfTerraria.Gear.hjson
Resolves: #700 
* Fixes item tool power tooltips by manually adding them through `GlobalItem::ModifyTooltips()`.
* Fixes item tooltip descriptors by creating a new localization key at `Mods.PathOfTerraria.Gear.Tooltips.None.Name`.
=> fix: fixes tool power tooltips and descriptors

Content/Items/Gear/Weapons/Staff/StaffHeldProjectile.cs
Resolves: #684 
* Fixes staff visuals while mounted by adjusting the center of the held projectile.
Adds additional rendering offsets to the held projectile to ensure compatibility with other mods.
=> fix: fixes staff visuals while mounted

Common/NPCs/AffixFreeNPCs.cs, Common/Systems/MobSystem/ArpgNPC.cs
Resolves: #702
- Disables affixes on anything that counts as a critter (`NPC.CountsAsCritter`), blacklists ballooned purple town slime
=> disable affixes on all invalid npcs

Common/UI/Guide/TutorialUIState.cs, Common/UI/Hotbar/NewHotbar.cs, Localization/en-US/Mods.PathOfTerraria.UI.hjson
Resolves: #728
Resolves: #729
- Adds in "No skill" text when hovering over an empty skill slot
- Levels up the player once before doing the tutorial step which requires a skill point
=> fix tutorial skill point issue, add in tooltip for missing skill

Content/Items/Gear/Weapons/Sword/Broadsword.cs, Content/Items/Gear/Weapons/Sword/CopperBroadsword.cs, Content/Items/Gear/Weapons/Sword/IronBroadsword.cs, Content/Items/Gear/Weapons/Sword/Katana.cs, Content/Items/Gear/Weapons/Sword/SteelBroadsword.cs
Broadswords were rather underpowered with how slow they would attack. The damage numbers have been tweaked drastically to fix this
Iron Broadsword 10 → 18
Steel Broadsword 12 → 38
Copper Broadsword  8 → 26
Katana was given a minimum area level to drop at 15as it was a very strong sword early game.
=> chore: do some broadsword rebalancing

Common/UI/Guide/TutorialUIState.cs
Resolves: #726 
* Adds a hacky workaround for positioning the guided tour quest GUI on very wide monitors
=> fix: Add a hacky workaround for ultra wides + 4k monitors for positioning the guided tour quest GUI

Content/Items/Consumables/Maps/BossMaps/PrimeMap.cs, Content/Items/Consumables/Maps/BossMaps/SkeletronMap.cs
- Fixes Skeletron Prime's map having no implementation for CanDrop
- Fixes Skeletron's map having the implementation that should be on Skeletron Prime
=> fix prime map unimpl., skeletron map candrop being prime condition

Common/UI/Guide/TutorialNPCs.cs, Common/UI/Guide/TutorialPlayer.cs, Common/UI/Guide/TutorialUIState.cs, Common/World/Generation/StructureTools.cs, Common/World/Passes/RavencrestEntrancePass.cs
Resolves: https://github.com/Path-of-Terraria/PathOfTerraria/issues/753
Resolves: #736 
- Makes the Ravencrest entrance avoid generating beyond the corruption/crimson, and disables surface corruption/crimson spawns for the duration of Guided Tour in the circumstance that it does
- Hides the active tutorial step when any dialogue is open
=> More favourable Ravencrest entrance gen

Common/UI/Guide/TutorialUIState.cs
Resolves: #750
*  remove base divisor when on large monitors - Not needed on 1440p or 4k so it was just throwing it off-screen
=> fix(#750): remove base divisor when on large monitors

Common/UI/Hotbar/NewHotbar.cs, Common/UI/PlayerStats/PlayerStatUIState.cs, Common/UI/Quests/QuestsUIState.cs, Common/UI/TreeState.cs, Content/Items/Gear/Weapons/Battleaxe/Battleaxe.cs, Content/Items/Gear/Weapons/Sword/Broadsword.cs, Content/Items/Gear/Weapons/Sword/Sword.cs, Core/Items/PoTGlobalItem.Tooltips.cs
Resolves: #786 
Resolves: #784
Resolves: #783
Resolves: #781
- Adjusts buff time left text to display properly
- Adds useTurn to all battleaxes, broadswords
- Add price & material tooltips to all items who use them
- Allows Quest, Tree, Stats UIs to be closed by hitting Escape
=> More misc qa fixes

Common/ItemDropping/ItemSpawner.cs, Common/NPCs/AffixFreeNPCs.cs, Common/Systems/ModPlayers/UniversalBuffingPlayer.cs, Core/Commands/SpawnMapCommand.cs
Resolves: #793
- Makes the Main Item (in terms of affixes) switch from the first inventory item to the mouse item when holding a mouse item
- Stops BoC's Creeper adds from having affixes, causing issues with the boss health bar
- Increased flexibility of `spawnmap` command
=> Even more misc fixes

Common/UI/Utilities/TabsUiState.cs, Common/UI/Utilities/UICloseablePanel.cs, Common/UI/Utilities/UITabsPanel.cs
- Fixes everything I needed to for the new trade UI in the online mod to work
There's still a couple of awkward things with the UI system I didn't reconcile.
Namely, UICloseablePanel and TabsUiState both define a `CreateMainPanel` virtual hook with different signatures, which causes implicit issues whenever TabsUiState is used. I didn't want to spend too much time working on that aspect of the issue as simply overriding the ClosablePanel's version fixes any issues, but there might want to be more insight given there. That being said, most issues are now fixed or at least mitigated.
=> misc fixes

Common/Subworlds/BossDomains/Hardmode/PrimeDomain.cs, Common/Subworlds/BossDomains/Hardmode/QueenSlimeDomain.cs, Common/Subworlds/BossDomains/Prehardmode/DeerclopsDomain.cs, Common/Subworlds/BossDomains/Prehardmode/EaterDomain.cs, Common/Subworlds/BossDomains/Prehardmode/EyeDomain.cs, Common/Subworlds/BossDomains/Prehardmode/SkeleDomain/RoomData.cs, Common/Subworlds/BossDomains/Prehardmode/WallOfFleshDomain.cs, Common/Subworlds/MappingAreas/ForestArea.cs, Common/World/Generation/StructureTools.cs
- Stops Ravencrest from crashing in MP
- Sets noSync to default to true in StructureTools.PlaceByOrigin, removes redundancies
While this fixes Ravencrest generation, this also infinitely hangs the server, requiring a force close. This may or may not be related, I have no idea.
=> Update structure placement, fix ravencrest in mp

Common/Subworlds/ArenaEnemyNPC.cs, Common/Systems/MiscUtilities/SpawnerSystem.cs
- Prevents arena NPCs from attempting to reset spawners when they have none
- Removed unused variable `ArenaEnemyNPC.SpawnerIndex`
=> Spawn record check

Common/UI/PlayerStats/PlayerStatInnerPanel.cs, Localization/en-US/Mods.PathOfTerraria.Items.hjson
Resolves: #896 
- Makes player stats scrollable
The way I implemented this uses a scrollbar that is invisible and not interactable, because the scrollbar was both really ugly and also didn't work at all for some reason. This might be a little awkward, but it works.
=> stat panel is now a scrolling list

Common/Waypoints/UI/UIWaypointMenu.cs
Resolves: #929 
Fixes needing to open arcane obelisk twice after closing it
Easy fix.
=> fix(#929): Fixes needing to open arcane obelisk twice after closing it

Common/Mechanics/Skill.Stats.cs, Common/Mechanics/Skill.cs, Common/Subworlds/RavencrestContent/RavencrestSystem.cs, Common/Systems/Affixes/ItemTypes/PassiveAffixes.cs, Common/Systems/EntityModifier.cs, Common/Systems/ModPlayers/SkillCombatPlayer.cs, Common/Systems/Questing/Quests/MainPath/HunterStartQuest.cs, Common/UI/GrimoireSelection/GrimoireSelectionUIState.cs, Common/UI/Guide/TutorialPlayer.cs, Common/UI/Guide/TutorialSystem.cs, Common/UI/Hotbar/NewHotbar.cs, Common/UI/PlayerStats/PlayerStatUIState.cs, Common/UI/Quests/QuestsUIState.cs, Common/UI/SkillsTree/AugmentSlotElement.cs, Common/UI/SkillsTree/SkillSelectionElement.cs, Content/Items/Gear/Weapons/Javelins/Bloodclotter.cs, Content/Items/Gear/Weapons/Javelins/Javelin.cs, Content/RoomTypes/Tavern.cs, Content/Skills/Magic/Fireball.cs, Content/Skills/Melee/MoltenShield.cs, Content/Skills/Ranged/BloodSiphon.cs, Content/Skills/Ranged/FetidCarapace.cs, Core/UI/SmartUI/IMutuallyExclusiveUI.cs, Core/UI/SmartUI/SmartUiLoader.cs, Localization/en-US/Mods.PathOfTerraria.Gear.hjson, Localization/en-US/Mods.PathOfTerraria.Items.hjson, Localization/en-US/Mods.PathOfTerraria.Skills.hjson
Resolves: #953
Resolves: #952
Resolves: #951
Resolves: #948
Resolves: #946
Resolves: #944
Resolves: #943
Resolves: #942
Resolves: #941
Resolves: #940
Resolves: #939
Resolves: #932
- Renamed Bat Wings to Pair of Bat Wings to differentiate between itself and vanilla Bat Wings
- Fix skills not having cooldowns
- Split skill CanEquipSkill to itself and ProtectedCanEquip, the latter being the hook - CanEquipSkill checks for mana consistently
- Added failReason for CanEquipSkill for clarity & user experience
- Fixed chests and signs in Ravencrest, giving text to signs
- Renamed EntityModifier.Attackspeed to AttackSpeed
- Fixed IncreasedAttackSpeedAffix being 100x stronger than it should lol
- Made Drawing the Bow quest reward a bow instead of two melee weapons
- Added …
=> Even more qa

Common/NPCs/ISpawnInRavencrestNPC.cs, Common/Subworlds/RavencrestContent/RavencrestSystem.cs, Common/Subworlds/RavencrestSubworld.cs, Content/NPCs/Town/BlacksmithNPC.cs, Content/NPCs/Town/EldricNPC.cs, Content/NPCs/Town/GarrickNPC.cs, Content/NPCs/Town/HunterNPC.cs, Content/NPCs/Town/MorganaNPC.cs, Content/NPCs/Town/WizardNPC.cs
Resolves: #984
- Adds in spawning conditions to ISpawnRavencrestNPC, defaulting to always on worldgen
- Eldric now spawns in his observatory after beating the King Slime
=> adds in custom spawning conditions for ISpawnInRavencrestNPC

Common/Systems/ModPlayers/ExpModPlayer.cs, Common/UI/Guide/TutorialUIState.cs, Content/Items/Gear/Weapons/Grimoire/GrimoireItem.cs, Content/NPCs/Town/MorganaNPC.cs
Resolves: #1030
Resolves: #1026
Resolves: #1025
Resolves: #1024
- Prevented the "Skip all" tutorial prompt from appearing if the player is already on the last step
- Fixed player level message and sounds activating for all clients
- Added the Grimoire to Morgana's shop after the initial is awarded
- Fixed Arcane Obelisk not being awarded when the "Skip all" tutorial prompt is used in multiplayer
- Fixed the Grimoire not being awarded by Morgana in multiplayer
=> Minor fixes

Common/Mechanics/Skill.cs, Common/Subworlds/BossDomains/Prehardmode/DeerDomain/DeerclopsSystem.cs, Common/Systems/Affixes/ItemTypes/SkillAffixes.cs, Common/Systems/ModPlayers/SkillCombatPlayer.cs, Common/UI/Armor/VanillaUIEdits.cs, Common/UI/Hotbar/NewHotbar.cs, Common/UI/SkillsTree/SkillSelectionElement.cs, Content/Projectiles/Ranged/BoomerangProjectile.cs, Content/Skills/Melee/MoltenShield.cs, Content/Skills/Ranged/BloodSiphon.cs, Content/Skills/Ranged/FetidCarapace.cs, Content/Skills/Ranged/RainOfArrows.cs, Localization/en-US/Mods.PathOfTerraria.SkillFailReasons.hjson, Localization/en-US/Mods.PathOfTerraria.Skills.hjson, Localization/ru-RU/Mods.PathOfTerraria.SkillFailReasons.hjson, Localization/ru-RU/Mods.PathOfTerraria.Skills.hjson
Resolves: #1147
Resolves: #1143
Resolves: #1129
Resolves: #1121
- Prevented boomerangs from traveling through walls unless they're returning to the player
- Skills no longer automatically unspec when `CanEquipSkill` isn't true. Instead, the skill's use is prevented for a reason provided by `SkillFailure`
- Fixed Deerclops compass coordinates not being synced in multiplayer
- Fixed the PvP button not being interactable from the proper position
=> QA changes

Common/UI/QuestPanelButton.cs
Resolves: #1131
- Changed the bounding box of the safe click to be 64x64 as previous params were drawing 2.5x length vertically down.
=> Fixed stat sheet button not being clickable

Common/Systems/MiscUtilities/OrbBreakingMessage.cs
Forgot to test for crimson AND corruption, canbreak is now checked in the breaking message.
Resolves: Softlock with Morven. Canbreak check had to be added in the message system
Added CanBreak check in the block breaking message so now Morven enjoyers can actually break the orbs.
I might be an idiot (:
=> Fixed softlock with morven

Content/Items/Consumables/Maps/BossMaps/FishronMap.cs
Resolves: Fishron map being queen bee domain instead.
protected override void OpenMapInternal()
{
SubworldSystem.Enter<FishronDomain>();
}
Change the above to FishronDomain instead.
=> Fixed fishron map domain being queen bee instead

Core/Items/PoTItemHelper.cs
Resolves: #794
- Prevented affixes with no value from being applied to items, most notably maps that are too low level to meet any affix tiers
=> Item affix value fix

Core/Items/PoTGlobalItem.Tooltips.cs
Resolves: #1205 
Resolves: #1231 
- Adds critical strike chance stat shown on weapons which should scale with all of your bonuses
- The damage stat should now update dynamically and show actual damage numbers (pre crits)
I included base weapon crit in the calcs even though Im pretty sure we arent adding any crit chance base to weapon atm? But if we ever decide to, it will be additive with your actual character crit chance
=> Added critical strike chance & scaling damage of weapons to tooltips

Common/NPCs/ISpawnInRavencrestNPC.cs, Common/NPCs/NPCSpawnTimeframe.cs, Common/Subworlds/RavencrestContent/RavencrestSystem.cs, Common/Subworlds/RavencrestSubworld.cs, Content/NPCs/Town/EldricNPC.cs
Resolves #1218
Ravencrest NPCs will now respawn over a short time period if they happen to be dead or missing.
This will print "has arrived" in chat. Should a separate key be made for "has returned"?
=> fix: Respawn Ravencrest NPCs if they die.

Common/UI/ExpBar.cs
Resolves: #1096 
- Clamped the draw of the experience bar fill to 100%
=> Exp bar no longer extends infinitely at 100

Common/Enums/ItemType.cs, Common/Systems/ModPlayers/AttributesPlayer.cs, Content/Items/Gear/Amulets/Amulet.cs
Changed damage class on dex to generic from melee
Resolves: #1256 
Makes dexterity bonus attack speed affect all damage types, not just melee.
=> Dexterity gives global AS

Content/NPCs/Town/EldricNPC.cs
Eldric's spawn condition was checking for EoC, while the wiki states that he should spawn after KS. Fascinating, since this seems to be the NPC that gives out the quest to kill EoC in the first place.
**Changelog:** Fixed Eldric's spawn condition requiring Eye of Cthulhu to be defeated, instead of King Slime.
=> fix: Fixed Eldric's spawn condition checking for EoC instead of KS.

Common/UI/Hotbar/HotbarHijack.cs, Common/UI/Hotbar/NewHotbar.cs, Common/UI/Tooltip.cs
Resolves #712
Resolves #1236
[Fixed mouse-item tooltips flickering when Frame Skip is set to Off.](https://github.com/Path-of-Terraria/PathOfTerraria/commit/c8aacd34a1389321db343028a456da36f7ac0546)
[Fixed hotbar potion tooltips not working.](https://github.com/Path-of-Terraria/PathOfTerraria/commit/65feca9109565e86d0f106a3a88195ea9a59e293)
There will be more, this is a split.
=> Tooltip fixes, batch 1.

Common/Systems/Affixes/AffixTooltipsHandler.cs
Resolves: #1235 #1232
- Multiple of the same affixes on one item are now added onto each other into one stat tooltip. This stops the weird affix comparison negative value bug from before.
In the future if we want to display them seperately we can, but it'd be cool to have an "Alt" advanced show item descriptions, which shows Affix Name / Tier / Stat Roll (like poe) and this could also seperate them into X on the tooltip
=> Fixed affixes being negative/hidden

Common/Subworlds/BossDomains/Hardmode/TwinsDomain.cs
- Adds an additional spawn point to the top of the Twins domain, enabled once the player gets there
=> add spawn to top of twins domain

Common/Subworlds/MappingAreas/ForestArea.cs, Common/UI/Armor/AccessorySlotGlobalItem.cs, Common/UI/Elements/UICustomHoverImageItemSlot.cs, Content/Items/Currency/CorruptShard.cs
- Fixes all items being unconsumable...unless they're equipped accessories
- Allowed Settings -> Return on Forest maps
- Major cleanup & code style fixes on AccessorySlotGlobalItem & UICustomHoverImageItemSlot
- Fixed dupe/deletion issue with accessories on the 3rd and 4th general slots
- Removed CorruptShard force-consume alongside fix of root issue (above)
=> fix consumability, minor fixes

.editorconfig, Common/Subworlds/BossDomains/Prehardmode/QueenBeeDomain.cs, Common/Subworlds/RavencrestContent/RavencrestSystem.cs, Common/Systems/ModPlayers/LivesSystem/BossDomainLivesPlayer.cs, Common/Systems/ModPlayers/LivesSystem/BossDomainLivesUILayer.cs, Common/World/Generation/Tools/GenerationUtilities.cs, Content/Items/Consumables/Maps/Map.cs, Content/Items/Gear/Weapons/WarShields/StarlightBulwark.cs
Resolves #1150
Resolves important issues adjacent to #1035, but could not reproduce the main issue. 
- Fixed boss domains' max lives counts desynchronizing between players in multiplayer - the first joining players' lives count will now be corrected when more players join the boss domain.
- Fixed Queen Bee's Domain's spawn position sometimes being put inside tiles.
- Fixed an issue with Ravencrest town NPCs respawns happening more rarely than intended.
- Fixed the Starlight Bulwark running client code on servers.
- Misc: Adjusted editorconfig to not complain about extra parentheses. Clarity of intent is everything.
=> Fix batch 2025-08-20

Common/Systems/ModPlayers/ExtraAccessoryModPlayer.cs, Common/UI/Armor/AccessorySlotGlobalItem.cs, Common/UI/Armor/Elements/UIArmorPage.cs, Common/UI/Armor/Elements/UIDefaultArmor.cs, Common/UI/Armor/Elements/UIDyeArmor.cs, Common/UI/Armor/Elements/UIVanityArmor.cs, Common/UI/Armor/UIArmorInventory.cs, Common/UI/Elements/UICustomHoverImageItemSlot.cs
Resolves #1300 
Resolves #1301
Resolves #1304
- Fixed a critical issue where right clicking a non-equippable item could equip or even duplicate it.
- Fixed a critical issue where right clicking an accessory could delete it forever.
- Fixed an issue that could lead to crashes in accessory-adjacent code of other mods such as Calamity's Vanities.
- Fixed hardmode accessory slots' unreachable items' effects being applied even in non-hardmode worlds.
- Fixed accessories put in extra accessory slots not being visible.
- Fixed right clicks not working on extra accessory slots.
- Some I may have fixed without knowing of, and some I may not recall.
**In need of testing:**
- (!) I have swapped the indices that vanity and dye slots point to. Does this make some previously equipped …
=> Critical fixes for custom accessory slots.

Common/Systems/MobSystem/ArpgNPC.cs, Common/Systems/MobSystem/HealthbarsNPC.cs, Common/UI/TooltipOverrides.cs, Core/Hooks/NpcTransformHooks.cs, Utilities/ILUtils.cs
Resolves #1209
Resolves #1303
Resolves #1309
- Fixed transforming NPCs (such as wall-crawling spiders) continuously growing in power by re-rolling rarities and affixes every time they transform. Very scary.
- Fixed some mouse texts, such as that of the ruler mode and minimap hovers, not displaying.
- Fixed tooltips not showing for item chat tags and similar mod elements
- Tooltips of dragged inventory items will now also display when hovering over item chat tags.
=> Fix batch 2025-08-21

Common/UI/Quests/QuestsUIState.cs
Resolves:
An old IsActive check was removed previously in #1311, which in the new version allowed all quests to be automatically added to quest log if they were available, without talking to NPCs. This is fixed now.
Tested with first few quests as well as the HM 0/10 queen slime quest and seems to work fine now.
=> Fixed how quests could be seen by default is they were "Active"

Content/NPCs/Mapping/Forest/GrovetenderBoss/Grovetender.Drawing.cs
This PR fixes #1201 
I can't see how this logically could happen, but never the less `SolidOrSlopedTile` is not save when x/y are out of bounds:
```cs
public static bool SolidOrSlopedTile(int x, int y) => SolidOrSlopedTile(Main.tile[x, y]);
```
So I've added bounds checking to prevent calling the method in these cases
=> Fix for #1201: prevent out of bounds on Grovetender PreDraw

Content/Items/Currency/EchoingShard.cs
This PR fixes #1234 
There's a Clone method, it's overridden on Map to set the `ItemLevel` and tier correctly, but it wasn't used in EchoingShard.cs
I've verified that corrupt items, uniques and cloned items can't be cloned.
Cloned maps correctly have the original item level and tier.
All other items (tested with rings and weapons) also correctly clone the original item.
> Echoing shard now correctly clones the original item, copying all stats, including item level and map tier.
=> Fix Echoing Shards on Maps rerolling the item level

Core/Items/ItemTooltips.cs, Localization/en-US/Mods.PathOfTerraria.Gear.hjson, Localization/es-ES/Mods.PathOfTerraria.Gear.hjson, Localization/fr-FR/Mods.PathOfTerraria.Gear.hjson, Localization/pl-PL/Mods.PathOfTerraria.Gear.hjson, Localization/pt-BR/Mods.PathOfTerraria.Gear.hjson, Localization/ru-RU/Mods.PathOfTerraria.Gear.hjson
Resolves: #1358 
- Tooltips now say “Explorable Map” or “Boss Map” instead of generic “Map”.
- Detection based on base classes: ExplorableMap vs BossMap.
- Implemented in Core/Items/ItemTooltips.cs; no impact on other items.
- Added localization keys for all supported locales.
- Keeps existing rarity/influence formatting intact.
=> Seperation of Explorable Map and Boss Map in Tooltip (#1358)

Core/Items/ItemTooltips.cs
Resolves: #1348
- Fixes the mana cost tooltip on weapons to display actual mana cost.
=> Fixes mana cost tooltip

Common/Systems/Affixes/AffixTooltips.cs, Common/Systems/Affixes/ItemAffix.cs, Core/Items/ItemTooltips.cs
Resolves:
- Implicit affixes will now be shown in a color different than that of rolled affixes.
- Internal: Publicized some methods for POTO to use.
=> Affix tooltip corrections.

Common/Systems/EntityModifier.cs, Common/Systems/ModPlayers/ProjectileModifierPlayer.cs, Content/Passives/Magic/SmallPassives/IncreasedMagicAndSummonDamagePassive.cs, Content/Passives/Magic/SmallPassives/IncreasedManaRegenerationRatePassive.cs, Content/Passives/Misc/ElementalResistancePassives.cs, Content/Passives/Misc/IncreasedAttackSpeedPassive.cs, Content/Passives/Misc/IncreasedProjectileCountPassive.cs, Content/Passives/Misc/IncreasedProjectileSpeedPassive.cs, Localization/de-DE/Mods.PathOfTerraria.Passives.hjson, Localization/en-US/Mods.PathOfTerraria.Passives.hjson, Localization/es-ES/Mods.PathOfTerraria.Passives.hjson, Localization/fr-FR/Mods.PathOfTerraria.Passives.hjson, Localization/pl-PL/Mods.PathOfTerraria.Passives.hjson, Localization/pt-BR/Mods.PathOfTerraria.Passives.hjson, Localization/ru-RU/Mods.PathOfTerraria.Passives.hjson
Resolves:
Adds the below passives
- Added lightning resistance
- Added fire resistance
- Added cold resistance
- Added all elemental resistances
- Increased magic & summon damage hybrid node
- Increased global attack speed %
- Increased projectile speed
- Increased projectile count
- Increased % mana regeneration rate
NOTE: These all still need the corresponding sprite/png to actually function. This is just code functionality.
**GRAPPLING HOOK NEEDS TO BE TESTED FOR PROJ SPEED/COUNT**
**SWORDS THAT SHOOT PROJECTILES NEED TO BE TESTED FOR PROJ SPEED/COUNT**
-Tested the res passives giving above 75 and its clamped no matter what so no issues there. 
-Tested additional projectiles fairly extensively, seems to work fine in 99% of cases. Some edge cases mentioned below.
-Bombs …
=> 9 new passives
